export const charMap = {
  "Ntpn-Regular": {
    filename: "Ntpn-Regular.ttf",
    chars: {
      a: "A",
      à: "à",
      â: "â",
      b: "B",
      c: "C",
      ç: "C",
      d: "D",
      e: "E",
      é: "é",
      è: "è",
      ê: "ê",
      f: "F",
      g: "G",
      h: "H",
      i: "I",
      î: "î",
      ï: "ï",
      j: "J",
      k: "K",
      l: "L",
      m: "M",
      n: "N",
      o: "O",
      ô: "ô",
      p: "P",
      q: "Q",
      r: "R",
      s: "S",
      t: "T",
      u: "U",
      û: "û",
      v: "V",
      w: "W",
      x: "X",
      y: "Y",
      z: "Z",
      "?": "interro",
      "'": "apostrophe",
      "%": "pourcentage",
      "/": "barre oblique",
      ":": "deuxpoints",
      "#": "hashtag",
      ".": "point",
      "!": "pt exclamation",
      ",": "virgule",
      "-": "tiret",
      "=": "égal",
      "≠": "inégal",
      0: "0",
      1: "1",
      2: "2",
      3: "3",
      4: "4",
      5: "5",
      6: "6",
      7: "7",
      8: "8",
      9: "9",
      λ: "clito",
      φ: "poing féministe",
    },
    helpedChars: {
      λ: "clito",
      φ: "poing féministe",
      "≠": "inégal",
    },
  },

  "Ntpn2-Regular": {
    filename: "Ntpn2-Regular.ttf",
    chars: {
      a: "A",
      à: "A",
      â: "A",
      b: "B",
      c: "C",
      ç: "C",
      d: "D",
      e: "E",
      é: "E",
      è: "E",
      ê: "E",
      f: "F",
      g: "G",
      h: "H",
      i: "I",
      î: "I",
      ï: "I",
      j: "J",
      k: "K",
      l: "L",
      m: "M",
      n: "N",
      o: "O",
      ô: "O",
      p: "P",
      q: "Q",
      r: "R",
      s: "S",
      t: "T",
      u: "U",
      û: "U",
      v: "V",
      w: "W",
      x: "X",
      y: "Y",
      z: "Z",
      '"': "openquote",
      "?": "interro",
      "'": "apostrophe",
      "%": "pourcentage",
      "/": "barre oblique",
      ":": "deuxpoints",
      "#": "hashtag",
      ".": "point",
      "!": "pt exclamation",
      ",": "virgule",
      "-": "tiret",
      "=": "égal",
      "≠": "inégal",
      0: "0",
      1: "1",
      2: "2",
      3: "3",
      4: "4",
      5: "5",
      6: "6",
      7: "7",
      8: "8",
      9: "9",
      λ: "clito",
      φ: "poing féministe",
      "«": "openquote",
      "»": "closequote",
      "…": "suspension",
    },
    helpedChars: {
      λ: "clito",
      φ: "poing féministe",
      "≠": "inégal",
      "«": "openquote",
      "»": "closequote",
      "…": "suspension",
    },
  },
};
